DROP TABLE Employees;

CREATE TABLE Employees (
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name VARCHAR(100) NOT NULL,
	surname VARCHAR(100) NOT NULL,
	birth DATE NOT NULL,
	salary INTEGER NOT NULL,
	intern BOOLEAN NOT NULL,
  PRIMARY KEY (id)
);
